### ISSUE TITLE
NEW FUCTION: Polygons of crowns

### ISSUE THREAD

**Issue by j-miszczyszyn** [DijoG/TREETOPS#4]
Hello,

did you consider to add function for creating polygons of the crown?

Best regards,
Jakub

**Comment by DijoG** [comment]
Dear Jakub,

there are some options implemented in the lidR package: _**dalponte2016()**_, _**li2012()**_, see "Segmentation of  the CHM" under Section 7.2: https://r-lidar.github.io/lidRbook/itd.html.
For treetop-controlled (i.e., marker-controlled) watershed segmentation you can use the _**ForestTools::mcws()**_ function, which is very nice since it requires an _sf_ object representing the treetops' coordinates (point data) as input. For more details, please refer to: https://search.r-project.org/CRAN/refmans/ForestTools/html/mcws.html. 

Take care,
Gergo
